version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT =${PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm start

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
